# Site settings
title: Road's Blog
SEOTitle: Road's Blog | 生活日常：好物、装机、diy、黑苹果、mini主机 | 这里是 @大马路叫Road 的个人博客，与你一起发现更大的世界。
header-img: img/home-bg.jpg
email: malu@road001.cn
description: "生活日常：好物、装机、diy、黑苹果、mini主机 | 这里是 @大马路叫Road 的个人博客，与你一起发现更大的世界。"
keyword: "马路, @大马路叫Road, Road‘s Blog, 博客, 个人网站, 好物, 装机, diy, 黑苹果, mini主机, Hackintosh, macOS"
url: "https://blog.malu.tech"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     superlulula
zhihu_username:     ma-lu-58
github_username:    Road-tech
facebook_username:  malu.tech
linkedin_username:  路-马-8ab580116

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: 
  - jekyll-paginate
  - jekyll-sitemap



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: blog-malu-tech

# Netease settings
#netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: c278b4039baa48e8bcc37c8269b4408e

# Google Analytics
ga_track_id: 'UA-183478702-1'            # Format: UA-xxxxxx-xx
ga_domain: malu.tech



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "喵喵喵？<br>Miao？"     # For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/100.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
# friends: [
#     {
#     #     title: "Su",
#     #     href: "http://su.gallery/"
#     # },{
#         title: "乱序",
#         href: "http://mida.re/"
#     },{
#         title: "Sherry Wu",
#         href: "https://xuechundesign.github.io"
#     }
# ]
